import{FISH,RARITIES}from'../config/fish-catalog.js';const $=id=>document.getElementById(id);export class HUD{constructor(engine){this.engine=engine;this.feed=[];this.globalCaught=new Set();this.bind();this.renderCatalog()}
bind(){$('catalogBtn').onclick=()=>$('catalogModal').showModal();$('closeCatalog').onclick=()=>$('catalogModal').close();$('fullscreenBtn').onclick=()=>document.fullscreenElement?document.exitFullscreen?.():document.documentElement.requestFullscreen?.()}
status(state){const e=$('connectionStatus'),map={connected:'PAINEL ON',connecting:'CONECTANDO',reconnecting:'RECONECTANDO',waiting:'AGUARDANDO CÓDIGO',error:'ERRO DE CONEXÃO'};e.textContent=map[state]||String(state).toUpperCase();e.classList.toggle('on',state==='connected')}
rules(rules=[]){const find=id=>rules.find(r=>String(r.actionId||'')===id);const c=find('fish_comment'),g=find('fish_gift');$('commentRule').textContent=c?(c.commentText||'CONFIGURADO'):'PESCA RNG';$('giftRule').textContent=g?(g.giftName||'CONFIGURADO'):'RNG + SORTE'}
onCatch(r){this.feed.unshift(r);this.feed=this.feed.slice(0,8);this.globalCaught.add(r.fish.id);this.renderStats();this.renderRank();this.renderFeed();this.renderCatalog()}
renderStats(){$('totalCatches').textContent=this.engine.totalCatches.toLocaleString('pt-BR');$('totalPlayers').textContent=this.engine.players.size.toLocaleString('pt-BR');$('catalogProgress').textContent=`${this.globalCaught.size}/${FISH.length}`}
renderRank(){const rows=this.engine.ranking(5);$('rankList').innerHTML=rows.length?rows.map((p,i)=>`<li><span>${['🥇','🥈','🥉','4º','5º'][i]}</span><b>${escapeHtml(p.user)}</b><strong>${p.points.toLocaleString('pt-BR')} pts</strong></li>`).join(''):'<li><span>🎣</span><b>Aguardando jogadores</b><strong>0 pts</strong></li>'}
renderFeed(){$('catchFeed').innerHTML=this.feed.length?this.feed.map(r=>`<div class="feed-item"><span>${r.fish.emoji}</span><b>${escapeHtml(r.user)} · ${escapeHtml(r.fish.name)}</b><strong>+${r.points}</strong></div>`).join(''):'<div class="feed-item"><span>🌊</span><b>Aguardando a primeira pesca</b><strong>—</strong></div>'}
renderCatalog(){$('catalogGrid').innerHTML=FISH.map(f=>{const seen=this.globalCaught.has(f.id),rar=RARITIES[f.rarity];return`<article class="fish-card ${seen?'':'locked'}"><span class="emo">${seen?f.emoji:'❔'}</span><div><b>${seen?escapeHtml(f.name):'Não descoberto'}</b><small style="color:${rar.color}">${rar.label}</small></div><strong>${f.points} pts</strong></article>`}).join('')}
reset(){this.feed=[];this.globalCaught.clear();this.renderStats();this.renderRank();this.renderFeed();this.renderCatalog()}}
function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}