import{FISH,RARITIES}from'../config/fish-catalog.js';const $=id=>document.getElementById(id);export class HUD{constructor(engine){this.engine=engine;this.feed=[];this.globalCaught=new Set();this.bind();this.renderCatalog()}
bind(){const catalog=$('catalogBtn'),close=$('closeCatalog');catalog?.addEventListener('click',()=>{const d=$('catalogModal');if(typeof d?.showModal==='function'&&!d.open)d.showModal()});close?.addEventListener('click',()=>{const d=$('catalogModal');if(d?.open)d.close()})}
status(state){const e=$('connectionStatus'),map={connected:'PAINEL ON',connecting:'CONECTANDO',reconnecting:'RECONECTANDO',waiting:'AGUARDANDO CÓDIGO',error:'ERRO DE CONEXÃO'};if(e){e.textContent=map[state]||String(state).toUpperCase();e.classList.toggle('on',state==='connected')}const live=$('liveHudStatus');if(live)live.textContent=state==='connected'?'PAINEL CONECTADO':state==='connecting'||state==='reconnecting'?'CONECTANDO':'PROJETO DANIEL'}
rules(rules=[]){const find=id=>rules.find(r=>String(r.actionId||'')===id);const c=find('fish_comment'),g=find('fish_gift');const ce=$('commentRule'),ge=$('giftRule');if(ce)ce.textContent=c?(c.commentText||'CONFIGURADO'):'PESCA RNG';if(ge)ge.textContent=g?(g.giftName||'CONFIGURADO'):'RNG + SORTE'}
onCatch(r){this.feed.unshift(r);this.feed=this.feed.slice(0,8);this.globalCaught.add(r.fish.id);this.renderStats();this.renderRank();this.renderFeed();this.renderCatalog()}
renderStats(){const c=$('totalCatches'),p=$('totalPlayers'),g=$('catalogProgress');if(c)c.textContent=this.engine.totalCatches.toLocaleString('pt-BR');if(p)p.textContent=this.engine.players.size.toLocaleString('pt-BR');if(g)g.textContent=`${this.globalCaught.size}/${FISH.length}`}
renderRank(){const rows=this.engine.ranking(5),list=$('rankList');if(!list)return;list.innerHTML=rows.length?rows.map((p,i)=>`<li><span>${['🥇','🥈','🥉','4º','5º'][i]}</span><b>${escapeHtml(p.user)}</b><strong>${p.points.toLocaleString('pt-BR')} pts</strong></li>`).join(''):'<li><span>🎣</span><b>Aguardando jogadores</b><strong>0 pts</strong></li>'}
renderFeed(){const feed=$('catchFeed');if(!feed)return;feed.innerHTML=this.feed.length?this.feed.map(r=>`<div class="feed-item"><span>${r.fish.emoji}</span><b>${escapeHtml(r.user)} · ${escapeHtml(r.fish.name)}</b><strong>+${r.points}</strong></div>`).join(''):'<div class="feed-item"><span>🌊</span><b>Aguardando a primeira pesca</b><strong>—</strong></div>'}
renderCatalog(){const grid=$('catalogGrid');if(!grid)return;grid.innerHTML=FISH.map(f=>{const seen=this.globalCaught.has(f.id),rar=RARITIES[f.rarity];return`<article class="fish-card ${seen?'':'locked'}"><span class="emo">${seen?f.emoji:'❔'}</span><div><b>${seen?escapeHtml(f.name):'Não descoberto'}</b><small style="color:${rar.color}">${rar.label}</small></div><strong>${f.points} pts</strong></article>`}).join('')}
reset(){this.feed=[];this.globalCaught.clear();this.renderStats();this.renderRank();this.renderFeed();this.renderCatalog()}}
function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}