const cleanCode=v=>String(v||'').toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,8);export const GAME_ID='live-fishing-rng';
export const manifest={protocol:'liveplus-game-manifest-v1',gameId:GAME_ID,name:'Live Fishing RNG',icon:'🎣',version:'0.1.0',actions:[{id:'fish_comment',label:'Pescar · Comentário',icon:'💬',description:'Executa uma pesca RNG para o usuário que comentou.'},{id:'fish_gift',label:'Pescar · Presente',icon:'🎁',description:'Executa pesca com bônus balanceado de sorte calculado pelo valor do presente.'},{id:'fish_test',label:'Pesca de teste',icon:'🧪',description:'Dispara uma pesca manual para validar o jogo.',params:[{id:'username',label:'Usuário',type:'text',default:'teste'}]},{id:'reset_session',label:'Zerar sessão',icon:'🧹',description:'Limpa ranking e progresso da sessão.'}]};
export class LivePlusConnection extends EventTarget{constructor({storagePrefix='fishing-rng'}={}){super();this.storagePrefix=storagePrefix;this.peer=null;this.conn=null;this.code='';this.token='';this.retry=0;this.timer=null;this.closed=false}
emit(type,detail={}){this.dispatchEvent(new CustomEvent(type,{detail}))}resolveCode(){const q=new URLSearchParams(location.search);return cleanCode(q.get('code')||q.get('session')||sessionStorage.getItem(this.storagePrefix+'-panel-code')||sessionStorage.getItem('1game-panel-code')||'')}
connect(raw=this.resolveCode()){const code=cleanCode(raw);if(code.length!==8){this.emit('status',{state:'waiting'});return false}if(typeof window.Peer!=='function'){this.emit('status',{state:'error'});return false}this.closed=false;this.code=code;this.token=sessionStorage.getItem(this.storagePrefix+'-session-token')||'';sessionStorage.setItem(this.storagePrefix+'-panel-code',code);this.open();return true}
open(){clearTimeout(this.timer);try{this.peer?.destroy()}catch{}this.emit('status',{state:this.retry?'reconnecting':'connecting'});this.peer=new Peer(undefined,{debug:0});this.peer.on('open',()=>{this.conn=this.peer.connect('liveplus-session-'+this.code.toLowerCase(),{reliable:true,serialization:'json'});this.conn.on('open',()=>this.conn.send({type:'session_hello',protocol:'liveplus-match-v1',token:this.token||undefined}));this.conn.on('data',d=>this.onData(d));this.conn.on('close',()=>this.reconnect());this.conn.on('error',()=>this.reconnect())});this.peer.on('error',()=>this.reconnect())}
onData(d){if(!d||typeof d!=='object')return;if(d.type==='session_accept'){this.retry=0;this.token=d.token||this.token;if(this.token)sessionStorage.setItem(this.storagePrefix+'-session-token',this.token);this.emit('status',{state:'connected',code:this.code});this.send({type:'game_manifest',protocol:'liveplus-game-manifest-v1',manifest});return}if(d.type==='rules_sync'){this.emit('rules',{rules:Array.isArray(d.rules)?d.rules:[]});return}if(d.type==='command')this.emit('command',d);else this.emit('message',d)}
reconnect(){if(this.closed)return;clearTimeout(this.timer);this.retry++;const delay=Math.min(5000,500*Math.pow(1.5,Math.min(this.retry,7)));this.emit('status',{state:'reconnecting',attempt:this.retry});this.timer=setTimeout(()=>this.open(),delay)}
send(payload){if(!this.conn?.open)return false;try{this.conn.send(payload);return true}catch{return false}}
sendState(state){return this.send({type:'state',gameId:GAME_ID,...state,at:Date.now()})}
sendEvent(event){return this.send({type:'event',gameId:GAME_ID,...event,at:Date.now()})}
disconnect(){this.closed=true;clearTimeout(this.timer);try{this.conn?.close()}catch{}try{this.peer?.destroy()}catch{}}}
export function eventUser(command={}){const e=command.event||{};return e.user||e.uniqueId||e.username||e.nickname||command.params?.username||'viewer'}
export function giftMeta(command={}){const e=command.event||{};return{diamonds:Number(e.diamondCount??e.diamonds??e.gift?.diamondCount??0)||0,count:Number(e.count??e.repeatCount??1)||1}}