const cleanCode=v=>String(v||'').toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,8);
export const formatCode=v=>{const c=cleanCode(v);return c.length>4?`${c.slice(0,4)}-${c.slice(4)}`:c};
export const GAME_ID='live-fishing-rng';
export const manifest={protocol:'liveplus-game-manifest-v1',gameId:GAME_ID,name:'Live Fishing RNG',icon:'🎣',version:'0.2.0',actions:[{id:'fish_comment',label:'Pescar · Comentário',icon:'💬',description:'Executa uma pesca RNG para o usuário que comentou.'},{id:'fish_gift',label:'Pescar · Presente',icon:'🎁',description:'Executa pesca com bônus balanceado de sorte calculado pelo valor do presente.'},{id:'fish_test',label:'Pesca de teste',icon:'🧪',description:'Dispara uma pesca manual para validar o jogo.',params:[{id:'username',label:'Usuário',type:'text',default:'teste'}]},{id:'pause_game',label:'Pausar jogo',icon:'⏸️',description:'Pausa o processamento visual das pescas; eventos recebidos ficam na fila.'},{id:'resume_game',label:'Continuar jogo',icon:'▶️',description:'Retoma o jogo e processa a fila de eventos.'},{id:'request_state',label:'Atualizar estado',icon:'🔄',description:'Solicita ao jogo o estado completo da sessão.'},{id:'reset_session',label:'Zerar sessão',icon:'🧹',description:'Limpa ranking e progresso da sessão.'}]};

export class LivePlusConnection extends EventTarget{
  constructor({storagePrefix='fishing-rng'}={}){super();this.storagePrefix=storagePrefix;this.peer=null;this.conn=null;this.code='';this.token='';this.retry=0;this.timer=null;this.handshakeTimer=null;this.closed=false;this.connected=false}
  emit(type,detail={}){this.dispatchEvent(new CustomEvent(type,{detail}))}
  resolveCode(){const q=new URLSearchParams(location.search);let saved='';try{saved=localStorage.getItem(this.storagePrefix+'-panel-code')||''}catch{}return cleanCode(q.get('code')||q.get('session')||sessionStorage.getItem(this.storagePrefix+'-panel-code')||saved||sessionStorage.getItem('1game-panel-code')||'')}
  tokenKey(code=this.code){return `${this.storagePrefix}-session-token:${cleanCode(code)}`}
  loadToken(){try{return sessionStorage.getItem(this.tokenKey())||''}catch{return''}}
  saveToken(token){this.token=String(token||'');try{sessionStorage.setItem(this.tokenKey(),this.token)}catch{}}
  saveCode(){try{sessionStorage.setItem(this.storagePrefix+'-panel-code',this.code);localStorage.setItem(this.storagePrefix+'-panel-code',formatCode(this.code))}catch{}}
  clearHandshake(){clearTimeout(this.handshakeTimer);this.handshakeTimer=null}
  cleanup(){clearTimeout(this.timer);this.timer=null;this.clearHandshake();try{this.conn?.close()}catch{}try{this.peer?.destroy()}catch{}this.conn=null;this.peer=null;this.connected=false}
  connect(raw=this.resolveCode()){const code=cleanCode(raw);if(code.length!==8){this.emit('status',{state:'waiting',code:''});return false}if(typeof window.Peer!=='function'){this.emit('status',{state:'error',reason:'PeerJS indisponível',code});return false}this.closed=false;this.code=code;this.token=this.loadToken();this.retry=0;this.saveCode();this.cleanup();this.closed=false;this.open();return true}
  open(){if(this.closed||!this.code)return;clearTimeout(this.timer);try{this.peer?.destroy()}catch{}this.emit('status',{state:this.retry?'reconnecting':'connecting',code:this.code,attempt:this.retry});this.peer=new Peer(undefined,{debug:0});
    const fail=reason=>{this.emit('status',{state:'error',reason:String(reason?.message||reason?.type||reason||'Falha de conexão'),code:this.code});this.reconnect()};
    this.peer.on('open',()=>{try{this.conn=this.peer.connect('liveplus-session-'+this.code.toLowerCase(),{reliable:true,serialization:'json'})}catch(e){fail(e);return}this.handshakeTimer=setTimeout(()=>{if(!this.connected&&!this.closed){this.emit('status',{state:'timeout',code:this.code});try{this.conn?.close()}catch{}this.reconnect()}},8000);this.conn.on('open',()=>{try{this.conn.send({type:'session_hello',protocol:'liveplus-match-v1',token:this.token||undefined})}catch(e){fail(e)}});this.conn.on('data',d=>this.onData(d));this.conn.on('close',()=>{this.connected=false;this.emit('status',{state:'disconnected',code:this.code});this.reconnect()});this.conn.on('error',fail)});
    this.peer.on('error',fail);this.peer.on('disconnected',()=>{try{this.peer.reconnect()}catch{this.reconnect()}})}
  onData(d){if(!d||typeof d!=='object')return;if(d.type==='session_accept'){this.clearHandshake();this.retry=0;this.connected=true;if(d.token)this.saveToken(d.token);this.emit('status',{state:'connected',code:this.code,exclusive:!!d.exclusive});this.sendManifest();return}if(d.type==='session_reject'){this.clearHandshake();this.connected=false;this.closed=true;this.emit('status',{state:'rejected',code:this.code,reason:d.reason||'Sessão recusada'});this.cleanup();return}if(d.type==='rules_sync'){this.emit('rules',{rules:Array.isArray(d.rules)?d.rules:[]});return}if(d.type==='command')this.emit('command',d);else this.emit('message',d)}
  reconnect(){if(this.closed||this.timer||!this.code)return;this.connected=false;this.clearHandshake();this.retry++;if(this.retry>8){this.emit('status',{state:'lost',code:this.code});return}const delay=Math.min(5000,600*Math.pow(1.55,Math.min(this.retry,7)));this.emit('status',{state:'reconnecting',code:this.code,attempt:this.retry,delay});this.timer=setTimeout(()=>{this.timer=null;this.open()},delay)}
  sendManifest(){return this.send({type:'game_manifest',protocol:'liveplus-game-manifest-v1',manifest})}
  send(payload){if(!this.conn?.open)return false;try{this.conn.send(payload);return true}catch{return false}}
  sendState(state){return this.send({type:'state',gameId:GAME_ID,...state,at:Date.now()})}
  sendEvent(event){return this.send({type:'event',gameId:GAME_ID,...event,at:Date.now()})}
  disconnect(){this.closed=true;const code=this.code;this.cleanup();this.emit('status',{state:'offline',code});return true}
}
export function eventUser(command={}){const e=command.event||{};return e.user||e.uniqueId||e.username||e.nickname||command.params?.username||'viewer'}
export function giftMeta(command={}){const e=command.event||{};return{diamonds:Number(e.diamondCount??e.diamonds??e.gift?.diamondCount??0)||0,count:Number(e.count??e.repeatCount??1)||1}}